download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/recordsansible-ara-0.1.0.tar.gz
format_version: 1.0.0
name: ara
namespace: recordsansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/recordsansible/ara/versions/0.1.0/
